### basic settings

# site properties and page defaults
title: Lindsay Lab
description: Artificial neural networks applied to psychology, neuroscience, and climate change
logo: images/logo_winner.jpg
header: images/background.jpg
footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  email: grace.lindsay@nyu.edu
  google-scholar: https://scholar.google.com/citations?user=4kETHY4AAAAJ&hl=en
  github: https://github.com/Lindsay-Lab
  twitter: @neurograce
  #instagram: YourLabHandle
  #youtube: YourLabChannel

# automatic citations -DO THIS
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
